"""
Blue Team Detection Pipeline
=====================================================================

Built directly against the REAL Red Team handoff:
  - reports/ato_corpus_raw.json   (97 ACCOUNT_TAKEOVER traces)
  - reports/app_corpus_raw.json   (156 AUTHORIZED_PUSH_PAYMENT traces)
  - reports/mule_corpus_raw.json  (121 MULE_NETWORK traces, 42 rings --
    generated by scripts/run_mule_network_qualification.py. Loaded the
    same way as ATO/APP with zero special-case code; if this file is
    missing, build_dataset() logs a warning and continues without it.)
  - red_team.world.world.NormalWorld  (legitimate / fraud=0 population)
  - red_team.schemas.observable.extract_observable  (official Red Team
    extractor â€” reused here so legitimate traces have EXACTLY the same
    shape as attack traces, with zero custom schema invented)

No PaySim, no mocked device_id, no invented flat schema anywhere in
this file. Every field used below is read directly from the real
observable_trace JSON structure.

--------------------------------------------------------------------
IMPORTANT FIX vs. the first version of this pipeline (v1 -> v2)
--------------------------------------------------------------------
v1 grouped a legitimate customer's ENTIRE multi-day event history into
one trace. That made legit traces span days (many logins, long window)
while attack traces span one tight episode (always exactly 1 login).
The model hit 100% recall â€” but mostly by learning "short observation
window / single login = attack", not by learning actual fraud
behavior. That is not a result you can defend to judges.

v2 fixes this by grouping Normal World events into per-SESSION traces
(one login -> its transactions -> logout), the same unit of granularity
an attack trace represents. DEVICE_REGISTRATION events (which have no
session_id in the schema) are attached to the nearest same-customer
session by time proximity. This removes the free "window length" and
"login count" shortcut and forces the model to learn from the
behavioral features the spec actually cares about (Section 4 and 11:
beneficiary timing, velocity, device timing, retry patterns).

An ablation check is included in the evaluation step: the model is
also scored with the structural "shortcut" features removed, so you
can see how much of its performance survives without them. Report
both numbers in the docx â€” that honesty is worth more to judges than
a single unexplained 100% recall figure.

--------------------------------------------------------------------
KNOWN, DOCUMENTED LIMITATION (do not silently paper over this)
--------------------------------------------------------------------
NormalWorld's legitimate event generator does not produce
BENEFICIARY_ADDITION events at all (verified empirically â€” 0 out of
6000+ generated events). That means, in the CURRENT dataset,
"a beneficiary was ever added" is a perfect separator by construction,
not because it's a strong real-world signal on its own. This is a Red
Team simulator scope gap, not something to fix by fabricating legit
beneficiary-addition events yourselves. State this explicitly in the
Solution Walkthrough: it is a known simulation boundary, and the
ablation results (which show performance without beneficiary/device
features) are the fairer number to lead with if a judge pushes on it.

Run from the repo root, with src/ on PYTHONPATH:

    PYTHONPATH=src python3 blue_team_pipeline.py

Outputs land in ./blue_team_output/
"""

from __future__ import annotations

import json
from collections import defaultdict
from datetime import datetime
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.calibration import CalibratedClassifierCV

from sklearn.frozen import FrozenEstimator
from sklearn.metrics import (
    average_precision_score,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
import joblib
import hashlib

# ---------------------------------------------------------------------------
# CONFIG
# ---------------------------------------------------------------------------
CONFIG = {
    "REPO_ROOT": Path(__file__).parent,
    "ATO_CORPUS_PATH": "reports/ato_corpus_raw.json",
    "APP_CORPUS_PATH": "reports/app_corpus_raw.json",
    "MULE_CORPUS_PATH": "reports/mule_corpus_raw.json",
    "OUTPUT_DIR": "blue_team_output",
    "NORMAL_WORLD_SEED": 7,
    "N_CUSTOMERS": 400,
    "N_MERCHANTS": 40,
    "N_BENEFICIARIES": 200,
    "N_LEGIT_EVENTS": 6000,
    "MIN_EVENTS_PER_TRACE": 2,
    "TEST_SIZE": 0.2,
    "RANDOM_STATE": 42,
    "DECISION_THRESHOLD": 0.5,
}

# Features that encode "shape of the observation window" rather than
# fraud behavior. Used for the ablation honesty-check in evaluate().
STRUCTURAL_SHORTCUT_FEATURES = [
    "window_seconds", "count_session_login", "transactions_per_session",
]


# ---------------------------------------------------------------------------
# Step 1 - Load the real attack corpora
# ---------------------------------------------------------------------------
def load_attack_corpus(path: Path, family_label: str) -> list[dict]:
    """Load one of the Red Team's raw corpus files.

    Every record is {"observable_trace": {...}, "ground_truth": {...}}.
    Per Section 3 of BLUE_TEAM_INTEGRATION_SPEC.md, every persisted
    record in these two files IS an attack by construction -- there is
    no separate is_fraud field to read. fraud=1 is applied here.
    """
    with open(path) as f:
        raw = json.load(f)

    records = []
    for rec in raw:
        records.append(
            {
                "trace_id": rec["observable_trace"]["trace_id"],
                "customer_id": rec["observable_trace"]["customer_id"],
                "events": rec["observable_trace"]["events"],
                "observation_window": rec["observable_trace"]["observation_window"],
                "fraud": 1,
                "attack_family": rec["ground_truth"]["attack_family"],
                "attack_difficulty": rec["ground_truth"]["attack_difficulty"],
            }
        )
    print(f"  loaded {len(records)} {family_label} traces from {path.name}")
    return records


# ---------------------------------------------------------------------------
# Step 2 - Build the legitimate (fraud=0) population, SESSION-windowed
# ---------------------------------------------------------------------------
def build_legitimate_traces(cfg: dict) -> list[dict]:
    """Generate Normal World activity and group it into per-SESSION
    traces (not per-customer) so legit traces are comparable in
    granularity to attack traces, which each represent one tight
    episode. Uses the Red Team's OWN extract_observable() function --
    no custom schema invented.
    """
    from red_team.world.world import NormalWorld
    from red_team.schemas.observable import extract_observable

    print("  generating Normal World legitimate population...")
    world = NormalWorld(seed=cfg["NORMAL_WORLD_SEED"])
    world.generate_population(
        n_customers=cfg["N_CUSTOMERS"],
        n_merchants=cfg["N_MERCHANTS"],
        n_beneficiaries=cfg["N_BENEFICIARIES"],
    )
    world.generate_legitimate_events(num_events=cfg["N_LEGIT_EVENTS"])
    events = world.get_events()


    # Split events into those with a session_id (SESSION_LOGIN,
    # SESSION_LOGOUT, TRANSACTION, BENEFICIARY_ADDITION if present) and
    # those without (DEVICE_REGISTRATION has no session_id in this
    # schema -- verified empirically).
    sessioned = [e for e in events if e.envelope.session_id is not None]
    sessionless = [e for e in events if e.envelope.session_id is None]

    by_session = defaultdict(list)
    for e in sessioned:
        by_session[e.envelope.session_id].append(e)

    # Attach sessionless events (device registrations) to the nearest
    # same-customer session by time proximity, mirroring how they'd
    # realistically be associated with a browsing episode.
    customer_sessions = defaultdict(list)  # customer_id -> [(session_id, min_ts)]
    for sid, evs in by_session.items():
        cid = evs[0].envelope.customer_id
        min_ts = min(e.envelope.timestamp for e in evs)
        customer_sessions[cid].append((sid, min_ts))

    for e in sessionless:
        cid = e.envelope.customer_id
        candidates = customer_sessions.get(cid, [])
        if not candidates:
            continue
        nearest_sid = min(candidates, key=lambda t: abs((t[1] - e.envelope.timestamp).total_seconds()))[0]
        by_session[nearest_sid].append(e)

    records = []
    for sid, evs in by_session.items():
        if len(evs) < cfg["MIN_EVENTS_PER_TRACE"]:
            continue
        evs_sorted = sorted(evs, key=lambda e: e.envelope.timestamp)
        trace = extract_observable(
            evs_sorted,
            trace_id=f"legit_sess_{sid}",
            merchant_lookup=world.state.merchants,
        )
        trace_dict = json.loads(trace.model_dump_json())
        records.append(
            {
                "trace_id": trace_dict["trace_id"],
                "customer_id": trace_dict["customer_id"],
                "events": trace_dict["events"],
                "observation_window": trace_dict["observation_window"],
                "fraud": 0,
                "attack_family": "legitimate",
                "attack_difficulty": "n/a",
            }
        )
    print(f"  built {len(records)} session-windowed legitimate traces "
          f"from {len(events)} raw events ({len(sessionless)} sessionless "
          f"events reattached by time proximity)")
    return records


# ---------------------------------------------------------------------------
# Step 3 - Feature engineering (Sections 4 and 11 of the integration spec)
# ---------------------------------------------------------------------------
def extract_features(record: dict) -> dict:
    events = sorted(record["events"], key=lambda e: e["timestamp"])
    feats = {"trace_id": record["trace_id"]}

    type_counts = defaultdict(int)
    for e in events:
        type_counts[e["event_type"]] += 1
    for t in ["TRANSACTION", "SESSION_LOGIN", "DEVICE_REGISTRATION", "BENEFICIARY_ADDITION"]:
        feats[f"count_{t.lower()}"] = type_counts.get(t, 0)
    feats["total_events"] = len(events)

    start = datetime.fromisoformat(record["observation_window"][0])
    end = datetime.fromisoformat(record["observation_window"][1])
    window_seconds = max((end - start).total_seconds(), 1.0)
    feats["window_seconds"] = window_seconds

    txns = [e for e in events if e["event_type"] == "TRANSACTION"]
    logins = [e for e in events if e["event_type"] == "SESSION_LOGIN"]
    benefs = [e for e in events if e["event_type"] == "BENEFICIARY_ADDITION"]
    devices = [e for e in events if e["event_type"] == "DEVICE_REGISTRATION"]

    # --- Velocity ---
    feats["transactions_per_hour"] = len(txns) / (window_seconds / 3600.0)
    if len(txns) >= 2:
        tx_times = [datetime.fromisoformat(t["timestamp"]) for t in txns]
        gaps = [(tx_times[i + 1] - tx_times[i]).total_seconds() for i in range(len(tx_times) - 1)]
        feats["mean_time_between_transactions"] = float(np.mean(gaps))
        feats["min_time_between_transactions"] = float(np.min(gaps))
    else:
        feats["mean_time_between_transactions"] = window_seconds
        feats["min_time_between_transactions"] = window_seconds

    # --- Session ---
    feats["transactions_per_session"] = len(txns) / max(len(logins), 1)
    if logins and txns:
        first_login = datetime.fromisoformat(logins[0]["timestamp"])
        first_txn = datetime.fromisoformat(txns[0]["timestamp"])
        feats["time_login_to_first_transaction"] = max((first_txn - first_login).total_seconds(), 0.0)
    else:
        feats["time_login_to_first_transaction"] = -1.0
    feats["login_attempt_count_max"] = max((l.get("login_attempt_count", 1) for l in logins), default=0)
    feats["auth_failure_present"] = int(any(l.get("auth_success") is False for l in logins))

    # --- Device (ATO-specific) ---
    feats["new_device_present"] = int(len(devices) > 0)
    if devices and txns:
        dev_time = datetime.fromisoformat(devices[0]["timestamp"])
        after = [datetime.fromisoformat(t["timestamp"]) for t in txns
                 if datetime.fromisoformat(t["timestamp"]) >= dev_time]
        feats["time_device_registration_to_transaction"] = (min(after) - dev_time).total_seconds() if after else -1.0
    else:
        feats["time_device_registration_to_transaction"] = -1.0

    # --- Beneficiary timing (spec's headline feature -- see module
    # docstring re: this being a perfect-separator artifact currently) ---
    feats["beneficiary_added_before_transaction"] = 0
    feats["time_from_beneficiary_add_to_transaction"] = -1.0
    if benefs and txns:
        beneficiary_time = datetime.fromisoformat(benefs[0]["timestamp"])
        later_txns = [datetime.fromisoformat(t["timestamp"]) for t in txns
                      if datetime.fromisoformat(t["timestamp"]) >= beneficiary_time]
        if later_txns:
            feats["beneficiary_added_before_transaction"] = 1
            feats["time_from_beneficiary_add_to_transaction"] = (min(later_txns) - beneficiary_time).total_seconds()

    # --- Failure / retry ---
    statuses = [t.get("transaction_status", "") for t in txns]
    feats["failed_transaction_count"] = sum(1 for s in statuses if s not in ("completed", "success", "posted"))
    feats["failed_then_completed"] = int(any(
        statuses[i] not in ("completed", "success", "posted") and statuses[i + 1] in ("completed", "success", "posted")
        for i in range(len(statuses) - 1)
    ))

    # --- Amount sequence ---
    amounts = [float(t["amount"]) for t in txns]
    if amounts:
        feats["amount_mean"] = float(np.mean(amounts))
        feats["amount_max"] = float(np.max(amounts))
        feats["amount_min"] = float(np.min(amounts))
        feats["amount_std"] = float(np.std(amounts))
        feats["amount_cv"] = feats["amount_std"] / max(feats["amount_mean"], 1e-6)
        if len(amounts) >= 2:
            feats["amount_change_after_failure"] = int(any(
                statuses[i] not in ("completed", "success", "posted") and amounts[i + 1] < amounts[i]
                for i in range(len(amounts) - 1)
            ))
            feats["amount_trend"] = float(np.sign(amounts[-1] - amounts[0]))
        else:
            feats["amount_change_after_failure"] = 0
            feats["amount_trend"] = 0.0
    else:
        feats.update({"amount_mean": 0.0, "amount_max": 0.0, "amount_min": 0.0, "amount_std": 0.0,
                       "amount_cv": 0.0, "amount_change_after_failure": 0, "amount_trend": 0.0})

    channels = {t.get("channel") for t in txns if t.get("channel")}
    feats["distinct_channels"] = len(channels)

    return feats


# ---------------------------------------------------------------------------
# Step 4 - Assemble the training table
# ---------------------------------------------------------------------------
def add_hesitation_delta(df: pd.DataFrame) -> pd.DataFrame:
    """HESITATION_DELTA -- a synthetic, honestly-labeled proxy for the
    "duress pause" signal real APP-fraud systems chase, built entirely
    from timestamps this pipeline already logs (NOT a claim of real
    keystroke/mouse biometrics, which this system has no sensors to
    observe).

    Raw signal: time_from_beneficiary_add_to_transaction (already
    extracted per-trace). This is normalized -- z-scored -- against
    each customer's OWN historical transaction pace
    (mean_time_between_transactions across that customer's other
    traces in this dataset), so a naturally slow/careful customer and
    a naturally fast one aren't judged on the same absolute clock.

    Honest fallbacks (documented, not silently defaulted):
      - No beneficiary-add event occurred in this trace at all ->
        neutral 0.0 (no opinion, not a guess).
      - Customer has only a single trace in the dataset (no history to
        build a per-customer baseline from -- a cold-start account) ->
        fall back to the population-wide baseline instead of dividing
        by a zero/undefined standard deviation.
    """
    df = df.copy()
    df["HESITATION_DELTA"] = 0.0

    grouped = df.groupby("customer_id")["mean_time_between_transactions"]
    baseline_mean = grouped.transform("mean")
    baseline_std = grouped.transform("std").fillna(0.0)

    global_mean = df["mean_time_between_transactions"].mean()
    global_std = df["mean_time_between_transactions"].std()
    if not global_std or np.isnan(global_std):
        global_std = 1.0

    cold_start = baseline_std <= 1e-6
    effective_mean = baseline_mean.where(~cold_start, global_mean)
    effective_std = baseline_std.where(~cold_start, global_std)
    effective_std = effective_std.replace(0.0, global_std)

    has_beneficiary = df["beneficiary_added_before_transaction"] == 1
    z = (df["time_from_beneficiary_add_to_transaction"] - effective_mean) / effective_std
    df.loc[has_beneficiary, "HESITATION_DELTA"] = z[has_beneficiary]
    # rows with no beneficiary-add event keep the neutral 0.0 set above

    return df


def build_dataset(cfg: dict) -> pd.DataFrame:
    repo_root = cfg["REPO_ROOT"]

    print("Loading Red Team attack corpora...")
    ato_records = load_attack_corpus(repo_root / cfg["ATO_CORPUS_PATH"], "ATO")
    app_records = load_attack_corpus(repo_root / cfg["APP_CORPUS_PATH"], "APP")

    mule_path = repo_root / cfg["MULE_CORPUS_PATH"]
    if mule_path.exists():
        mule_records = load_attack_corpus(mule_path, "MULE_NETWORK")
    else:
        # Not a hard failure -- lets the pipeline still run against just
        # ATO/APP if reports/mule_corpus_raw.json hasn't been generated yet
        # (see scripts/run_mule_network_qualification.py).
        print(f"  WARNING: {mule_path.name} not found, skipping MULE_NETWORK "
              f"traces. Run scripts/run_mule_network_qualification.py first "
              f"to include them.")
        mule_records = []

    print("Building legitimate population (session-windowed)...")
    legit_records = build_legitimate_traces(cfg)

    all_records = ato_records + app_records + mule_records + legit_records
    print(f"Total traces: {len(all_records)} "
          f"({len(ato_records)} ATO + {len(app_records)} APP + "
          f"{len(mule_records)} MULE_NETWORK + {len(legit_records)} legit)")

    print("Extracting features...")
    rows = []
    for rec in all_records:
        feats = extract_features(rec)
        feats["fraud"] = rec["fraud"]
        feats["attack_family"] = rec["attack_family"]
        feats["attack_difficulty"] = rec["attack_difficulty"]
        feats["customer_id"] = rec["customer_id"]
        rows.append(feats)

    df = pd.DataFrame(rows)
    print("Computing HESITATION_DELTA (per-customer pacing baseline)...")
    df = add_hesitation_delta(df)
    return df


FEATURE_COLS = [
    "count_transaction", "count_session_login", "count_device_registration",
    "count_beneficiary_addition", "total_events", "window_seconds",
    "transactions_per_hour", "mean_time_between_transactions",
    "min_time_between_transactions", "transactions_per_session",
    "time_login_to_first_transaction", "login_attempt_count_max",
    "auth_failure_present", "new_device_present",
    "time_device_registration_to_transaction",
    "beneficiary_added_before_transaction",
    "time_from_beneficiary_add_to_transaction",
    "failed_transaction_count", "failed_then_completed",
    "amount_mean", "amount_max", "amount_min", "amount_std", "amount_cv",
    "amount_change_after_failure", "amount_trend", "distinct_channels",
    "HESITATION_DELTA",
]


# ---------------------------------------------------------------------------
# Identity-stable K-fold (fixes the Round1 -> Round2 phantom-regression bug)
#
# StratifiedKFold.split(X, y) assigns folds by POSITION in the array. That
# means fold membership is an accident of row order, not a property of the
# record itself. Append new hard-example rows later (as retrain_round2.py
# does) and every existing row can silently land in a DIFFERENT fold than it
# did in Round 1 -- any score delta you then measure is partly just fold
# reshuffling, not real model improvement or regression. stable_fold fixes
# this at the root: fold membership is derived from a hash of the record's
# own trace_id, so it can never change no matter what gets appended around
# it later.
# ---------------------------------------------------------------------------
def stable_fold_id(trace_id: str, random_state: int) -> int:
    """Deterministic hash of a record's own identity (trace_id), salted
    with random_state so different seeds still produce different-but-
    reproducible partitions. Never depends on array position."""
    h = hashlib.sha256(f"{random_state}:{trace_id}".encode("utf-8")).hexdigest()
    return int(h[:16], 16)


def stable_kfold_split(df: pd.DataFrame, y_col: str, n_splits: int, random_state: int,
                        trace_id_col: str = "trace_id"):
    """Drop-in replacement for StratifiedKFold(...).split(X, y): same
    (train_idx, test_idx) positional-index contract consumers already
    expect, but fold membership is computed from each row's own trace_id
    hash rather than its position in the array.

    Stratification is preserved by ranking each class's rows independently
    by their stable hash and assigning fold = rank % n_splits within that
    class -- so class balance across folds stays close to StratifiedKFold's
    guarantee, without positional dependence. Emits a warning if any fold's
    fraud rate still drifts more than 10 percentage points from the true
    rate (possible with very small classes), since stable_fold trades a
    small amount of stratification precision for identity stability.
    """
    df = df.reset_index(drop=True)
    n = len(df)
    fold_assignment = np.empty(n, dtype=int)
    true_rate = float(df[y_col].mean())

    for label in df[y_col].unique():
        sub_idx = df.index[df[y_col] == label].to_numpy()
        ranked = sorted(
            sub_idx,
            key=lambda i: stable_fold_id(str(df.at[i, trace_id_col]), random_state),
        )
        for rank, i in enumerate(ranked):
            fold_assignment[i] = rank % n_splits

    folds = []
    for fold in range(n_splits):
        test_mask = fold_assignment == fold
        test_idx = np.where(test_mask)[0]
        train_idx = np.where(~test_mask)[0]
        fold_rate = float(df.loc[test_idx, y_col].mean()) if len(test_idx) else 0.0
        if abs(fold_rate - true_rate) > 0.10:
            print(f"  [stable_fold WARNING] fold {fold} fraud rate {fold_rate:.3f} "
                  f"drifts >10pp from true rate {true_rate:.3f} (n={len(test_idx)})")
        folds.append((train_idx, test_idx))
    return folds


# ---------------------------------------------------------------------------
# Step 5 - Train
# ---------------------------------------------------------------------------
def train_model(df: pd.DataFrame, cfg: dict, feature_cols: list[str]):
    train_df, test_df = train_test_split(
        df, test_size=cfg["TEST_SIZE"], random_state=cfg["RANDOM_STATE"], stratify=df["fraud"],
    )
    X_train, y_train = train_df[feature_cols], train_df["fraud"]
    X_test, y_test = test_df[feature_cols], test_df["fraud"]

    base_model = XGBClassifier(
        n_estimators=200, max_depth=4, learning_rate=0.08,
        subsample=0.9, colsample_bytree=0.9, eval_metric="aucpr",
        random_state=cfg["RANDOM_STATE"], n_jobs=1, tree_method="exact",
    )
    base_model.fit(X_train, y_train)
    calibrator = CalibratedClassifierCV(
    FrozenEstimator(base_model),
    method="isotonic"
)
    calibrator.fit(X_train, y_train)

    return base_model, calibrator, train_df, test_df


# ---------------------------------------------------------------------------
# Step 6 - Evaluate (family- and difficulty-stratified, per Section 10)
# ---------------------------------------------------------------------------
def block(y_true, y_pred, y_proba):
    if len(set(y_true)) < 2:
        return {"n": len(y_true), "note": "single class in this slice -- metrics undefined"}
    return {
        "n": int(len(y_true)),
        "precision": float(precision_score(y_true, y_pred, zero_division=0)),
        "recall": float(recall_score(y_true, y_pred, zero_division=0)),
        "f1": float(f1_score(y_true, y_pred, zero_division=0)),
        "roc_auc": float(roc_auc_score(y_true, y_proba)),
        "pr_auc": float(average_precision_score(y_true, y_proba)),
    }


def evaluate(model, test_df: pd.DataFrame, feature_cols: list[str], threshold: float) -> tuple[dict, np.ndarray, np.ndarray]:
    X_test = test_df[feature_cols]
    y_test = test_df["fraud"].values
    proba = model.predict_proba(X_test)[:, 1]
    preds = (proba >= threshold).astype(int)

    results = {"overall": block(y_test, preds, proba)}
    results["overall"]["confusion_matrix"] = confusion_matrix(y_test, preds).tolist()

    results["by_family"] = {}
    for fam in test_df["attack_family"].unique():
        if fam == "legitimate":
            continue
        fam_mask = test_df["attack_family"] == fam
        legit_mask = test_df["fraud"] == 0
        combined = test_df[fam_mask | legit_mask]
        pos = [test_df.index.get_loc(i) for i in combined.index]
        results["by_family"][fam] = block(combined["fraud"].values, preds[pos], proba[pos])

    results["by_family_difficulty"] = {}
    for fam in test_df["attack_family"].unique():
        if fam == "legitimate":
            continue
        for diff in ["easy", "medium", "hard", "advanced"]:
            fam_diff_mask = (test_df["attack_family"] == fam) & (test_df["attack_difficulty"] == diff)
            if fam_diff_mask.sum() == 0:
                continue
            legit_mask = test_df["fraud"] == 0
            combined = test_df[fam_diff_mask | legit_mask]
            pos = [test_df.index.get_loc(i) for i in combined.index]
            entry = block(combined["fraud"].values, preds[pos], proba[pos])
            entry["fraud_sample_size_warning"] = bool(fam_diff_mask.sum() < 10)
            results["by_family_difficulty"][f"{fam}_{diff}"] = entry

    return results, proba, preds


def cross_validated_evaluate(df: pd.DataFrame, cfg: dict, feature_cols: list[str], n_splits: int = 5) -> dict:
    """A single 80/20 split on ~1,450 rows is too small a sample to
    trust a perfect score in isolation -- it could easily be a lucky
    split. This runs stratified K-fold CV and pools out-of-fold
    predictions across the WHOLE dataset (every row gets scored by a
    model that never saw it during training), which is the honest way
    to report a number this small a dataset can defend.
    """
    folds = stable_kfold_split(df, "fraud", n_splits, cfg["RANDOM_STATE"])
    oof_proba = np.zeros(len(df))
    X, y = df[feature_cols].values, df["fraud"].values

    for train_idx, test_idx in folds:
        model = XGBClassifier(
            n_estimators=200, max_depth=4, learning_rate=0.08,
            subsample=0.9, colsample_bytree=0.9, eval_metric="aucpr",
            random_state=cfg["RANDOM_STATE"], n_jobs=1, tree_method="exact",
        )
        model.fit(X[train_idx], y[train_idx])
        oof_proba[test_idx] = model.predict_proba(X[test_idx])[:, 1]

    preds = (oof_proba >= cfg["DECISION_THRESHOLD"]).astype(int)
    results = {"overall": block(y, preds, oof_proba)}
    results["overall"]["confusion_matrix"] = confusion_matrix(y, preds).tolist()

    results["by_family"] = {}
    for fam in df["attack_family"].unique():
        if fam == "legitimate":
            continue
        mask = (df["attack_family"] == fam) | (df["fraud"] == 0)
        idx = df[mask].index.to_numpy()
        results["by_family"][fam] = block(y[idx], preds[idx], oof_proba[idx])

    results["by_family_difficulty"] = {}
    for fam in df["attack_family"].unique():
        if fam == "legitimate":
            continue
        for diff in ["easy", "medium", "hard", "advanced"]:
            fd_mask = (df["attack_family"] == fam) & (df["attack_difficulty"] == diff)
            if fd_mask.sum() == 0:
                continue
            mask = fd_mask | (df["fraud"] == 0)
            idx = df[mask].index.to_numpy()
            entry = block(y[idx], preds[idx], oof_proba[idx])
            entry["fraud_sample_size_warning"] = bool(fd_mask.sum() < 10)
            results["by_family_difficulty"][f"{fam}_{diff}"] = entry

    return results, oof_proba, preds


# ---------------------------------------------------------------------------
# Step 6.5 -- Cascaded detection (Stage 1: cheap rule filter, Stage 2: XGBoost)
#
# Real fraud systems don't run an expensive ML model on every single
# transaction -- they triage cheaply first. Stage 1 here is a
# deterministic, sub-millisecond rule filter with thresholds computed
# directly from this dataset's actual percentiles (see the analysis
# that produced these numbers -- legit p90 min_time_between_transactions
# is ~82,000s vs fraud median ~20s, a huge gap). Stage 1 only needs to
# be HIGH RECALL, not precise -- its job is to cheaply clear the bulk
# of obviously-legitimate traffic so Stage 2 (the trained model) only
# has to run on what's actually ambiguous.
# ---------------------------------------------------------------------------
def stage1_rule_filter(row) -> bool:
    """Returns True = escalate to Stage 2 ML model. False = auto-clear
    as legitimate without ever calling the ML model.

    Thresholds were derived empirically from this dataset's legit vs.
    fraud percentile gap (see repo analysis), not picked arbitrarily:
      - beneficiary_added_before_transaction: near-perfect separator
        in the CURRENT dataset (documented limitation -- NormalWorld
        doesn't generate legit beneficiary additions at all, see
        module docstring). Still a real-world-plausible rule (a payee
        added and paid within the same session is a classic ATO/APP
        signature), just currently over-clean in this simulator.
      - new_device_present: same caveat, same real-world plausibility.
      - min_time_between_transactions < 3600s: legit p90 is ~82,223s;
        fraud median is ~20s. Wide, safe margin.
      - transactions_per_hour > 2.5: just above legit p99 (~2.34).
    """
    return bool(
        row["beneficiary_added_before_transaction"] == 1
        or row["new_device_present"] == 1
        or row["min_time_between_transactions"] < 3600
        or row["transactions_per_hour"] > 2.5
    )


def compute_stage_1_2_cascade(df: pd.DataFrame, feature_cols: list[str], cfg: dict,
                               n_splits: int = 5):
    """
    Single source of truth for the Stage 1 (rule filter) -> Stage 2
    (XGBoost) out-of-fold cascade score. EvaluationHarness.run() calls this
    directly (see below) so the "official" Stage 1+2 cascade number and
    every downstream stage that builds on top of it (Stage 3 GCN, Stage 4
    autoencoder, Stage 5 Risk Fusion, Stage 6 decision policy,
    explainability) are guaranteed to use the IDENTICAL score and the
    IDENTICAL fold partition -- never two independently-reimplemented
    copies that could silently drift apart.

    Returns
    -------
    cascade_proba : (n,) float array -- out-of-fold Stage 1+2 score (0.0 for
                     rows Stage 1 auto-cleared without ever calling the
                     model; every other row is scored by a fold that never
                     trained on it).
    escalate      : (n,) bool array -- Stage 1's escalate/auto-clear
                     decision for each row.
    folds         : list of (train_idx, test_idx) tuples -- the exact
                     stable_kfold_split partition used (identity-stable,
                     keyed off each row's own trace_id -- see stable_fold_id
                     docstring), so downstream stages (GCN, autoencoder,
                     fusion meta-model) can train/test on IDENTICAL rows per
                     fold rather than a partition that merely happens to use
                     a matching random_state, and so appending new
                     hard-example rows later can never reshuffle an existing
                     row into a different fold.
    """
    X, y = df[feature_cols].values, df["fraud"].values

    escalate = df.apply(stage1_rule_filter, axis=1).values
    cascade_proba = np.zeros(len(df))
    folds = stable_kfold_split(df, "fraud", n_splits, cfg["RANDOM_STATE"])

    for train_idx, test_idx in folds:
        # Stage 2 model still trains on ALL training rows (general
        # model), mirroring how you'd retrain periodically on full
        # traffic even though inference-time only scores escalated rows.
        model = XGBClassifier(
            n_estimators=200, max_depth=4, learning_rate=0.08,
            subsample=0.9, colsample_bytree=0.9, eval_metric="aucpr",
            random_state=cfg["RANDOM_STATE"], n_jobs=1, tree_method="exact",
        )
        model.fit(X[train_idx], y[train_idx])

        for i in test_idx:
            if escalate[i]:
                cascade_proba[i] = model.predict_proba(X[i:i+1])[:, 1][0]
            else:
                cascade_proba[i] = 0.0  # auto-cleared, never scored by ML

    return cascade_proba, escalate, folds


class EvaluationHarness:
    """Formal ground-truth wall + cascade evaluator.

    Enforces the same isolation principle as the Red Team's own
    ground-truth separation: ground_truth (fraud label, family,
    difficulty) is NEVER exposed to the model at prediction time, only
    used afterward to score. This class wraps the full two-stage
    cascade (rule filter -> XGBoost) and reports metrics for the
    cascade AS A WHOLE, plus per-stage diagnostics so you can see
    exactly what each stage contributes and what it costs.
    """

    def __init__(self, feature_cols: list[str], cfg: dict):
        self.feature_cols = feature_cols
        self.cfg = cfg

    def run(self, df: pd.DataFrame, n_splits: int = 5) -> dict:
        cascade_proba, escalate, folds = compute_stage_1_2_cascade(
            df, self.feature_cols, self.cfg, n_splits=n_splits
        )
        y = df["fraud"].values

        preds = (cascade_proba >= self.cfg["DECISION_THRESHOLD"]).astype(int)

        results = {"overall": block(y, preds, cascade_proba)}
        results["overall"]["confusion_matrix"] = confusion_matrix(y, preds).tolist()

        # Stage-1-only diagnostics -- the ceiling and the cost saving
        fraud_mask = y == 1
        legit_mask = y == 0
        results["stage1_diagnostics"] = {
            "stage1_recall_on_fraud_ceiling": float(escalate[fraud_mask].mean()),
            "stage1_fraud_missed_permanently": int((~escalate[fraud_mask]).sum()),
            "stage1_legit_escalation_rate": float(escalate[legit_mask].mean()),
            "stage1_legit_autoclear_rate_cost_saving": float((~escalate[legit_mask]).mean()),
            "note": "stage1_recall_on_fraud_ceiling is the cascade's hard recall "
                    "ceiling -- Stage 2 can never catch what Stage 1 auto-clears.",
        }

        results["by_family"] = {}
        for fam in df["attack_family"].unique():
            if fam == "legitimate":
                continue
            mask = (df["attack_family"] == fam) | (df["fraud"] == 0)
            idx = df[mask].index.to_numpy()
            results["by_family"][fam] = block(y[idx], preds[idx], cascade_proba[idx])

        return results, cascade_proba, preds, escalate


# ---------------------------------------------------------------------------
# Step 8 -- GNN layer (Graph Convolutional Network, hand-implemented in NumPy)
#
# WHY NUMPY INSTEAD OF PYTORCH/TORCH-GEOMETRIC: deliberately avoided. A GPU
# deep-learning framework is a large, sometimes fragile dependency (this was
# confirmed painful on the dev machine used for this project, which already
# hit multiple Python/sklearn version conflicts). This GCN layer is small
# enough that a hand-derived, hand-verified NumPy implementation is both
# safer to install anywhere and easier to audit -- the backprop math below
# was verified against a toy problem before being trusted on real data
# (see project notes). It implements the same core operation as a standard
# GCN layer (Kipf & Welling): H_out = ReLU(A_hat @ X @ W + b), where A_hat
# is the symmetric-normalized adjacency matrix with self-loops.
#
# WHY A SYNTHETIC RING OVERLAY IS INJECTED FIRST: the real Red Team corpus,
# as delivered, has ZERO devices or beneficiaries shared across different
# customers (verified empirically -- every entity belongs to exactly one
# customer). A GNN's entire value proposition is learning from shared
# entities across otherwise-unrelated accounts (the classic real-world
# catch: multiple unrelated accounts paying the same mule beneficiary, or
# multiple takeover victims funneled through the same attacker device).
# Without that connectivity, a GNN has nothing to propagate and degenerates
# into a worse tabular classifier. This overlay is a CLEARLY DOCUMENTED,
# CLEARLY LABELED demonstration pattern (every injected trace carries a
# `synthetic_ring` tag, excluded from all normal training features, used
# only for this ablation comparison) representing a known real fraud
# pattern (mule rings / device farms) that the current Red Team simulator
# does not yet generate on its own. State this explicitly in the docx --
# this is future-work handoff material for Laxman's simulator, not
# something to present as if it were in the base corpus.
# ---------------------------------------------------------------------------
def inject_synthetic_rings(records: list[dict], family: str, entity_event_type: str,
                            entity_field: str, n_rings: int = 3, ring_size: int = 4,
                            seed: int = 99) -> list[dict]:
    rng = np.random.RandomState(seed)
    candidates = [r for r in records if any(e["event_type"] == entity_event_type for e in r["events"])]
    rng.shuffle(candidates)
    selected = candidates[: n_rings * ring_size]
    ring_ids = [f"synthetic_ring_{family}_{i}" for i in range(n_rings)]
    for idx, rec in enumerate(selected):
        ring_id = ring_ids[idx // ring_size]
        shared_val = f"{entity_field}_{ring_id}"
        for e in rec["events"]:
            if e["event_type"] == entity_event_type:
                e[entity_field] = shared_val
        rec["synthetic_ring"] = ring_id
    for rec in records:
        rec.setdefault("synthetic_ring", None)
    print(f"  injected {len(selected)} {family} traces into {n_rings} rings of size {ring_size} "
          f"(clearly tagged, excluded from tabular features -- see module docstring)")
    return records


def sync_device_ids_for_rings(records: list[dict]) -> list[dict]:
    """After injecting a shared device_id on SESSION_LOGIN events for a ring,
    propagate the same device_id onto that trace's SESSION_LOGOUT / DEVICE_
    REGISTRATION events so the trace is internally consistent."""
    for rec in records:
        if rec.get("synthetic_ring"):
            login_devs = [e["device_id"] for e in rec["events"] if e["event_type"] == "SESSION_LOGIN"]
            if login_devs:
                shared = login_devs[0]
                for e in rec["events"]:
                    if e["event_type"] in ("SESSION_LOGOUT", "DEVICE_REGISTRATION") and "device_id" in e:
                        e["device_id"] = shared
    return records


def build_cross_customer_adjacency(records: list[dict]) -> np.ndarray:
    """Trace-trace adjacency: an edge exists ONLY when two traces belonging
    to DIFFERENT customers share a device_id or beneficiary_id. Same-customer
    reuse of their own device across sessions is explicitly excluded -- that
    is normal behavior, not a ring signal, and including it was an early bug
    caught during development (it produced ~1,360/1,458 "connected" nodes,
    almost entirely spurious same-customer edges)."""
    N = len(records)
    device_owner = defaultdict(list)
    benef_owner = defaultdict(list)
    for i, rec in enumerate(records):
        for e in rec["events"]:
            if "device_id" in e:
                device_owner[e["device_id"]].append((i, rec["customer_id"]))
            if e["event_type"] == "BENEFICIARY_ADDITION":
                benef_owner[e["beneficiary_id"]].append((i, rec["customer_id"]))

    A = np.eye(N)
    for owner_map in (device_owner, benef_owner):
        for entity, trace_cust_list in owner_map.items():
            if len({c for _, c in trace_cust_list}) > 1:
                for a_i, a_c in trace_cust_list:
                    for b_i, b_c in trace_cust_list:
                        if a_i != b_i and a_c != b_c:
                            A[a_i, b_i] = 1
    return A


def normalize_adjacency(A: np.ndarray) -> np.ndarray:
    D = A.sum(axis=1)
    D_inv_sqrt = np.diag(1.0 / np.sqrt(D))
    return D_inv_sqrt @ A @ D_inv_sqrt


class NumpyGCN:
    """A single-layer Graph Convolutional Network, hand-implemented with a
    manually derived (and toy-problem-verified) backprop. Deliberately
    simple -- see module docstring for why this exists instead of using a
    GNN framework. NOT intended to replace the XGBoost detector: its value
    is specifically on graph-connected (ring-structured) fraud, and the
    recommended production design is to feed its output as an additional
    signal into the tabular ensemble, not to deploy it standalone (see the
    ring-subset vs. no-graph ablation results this script prints).
    """

    def __init__(self, n_features: int, hidden_dim: int = 16, seed: int = 0):
        rng = np.random.RandomState(seed)
        self.W1 = rng.randn(n_features, hidden_dim) * np.sqrt(2.0 / n_features)
        self.b1 = np.zeros(hidden_dim)
        self.W2 = rng.randn(hidden_dim, 1) * np.sqrt(2.0 / hidden_dim)
        self.b2 = np.zeros(1)

    def fit(self, A_hat: np.ndarray, X: np.ndarray, y: np.ndarray, train_idx: np.ndarray,
            epochs: int = 400, lr: float = 0.05):
        mask = np.zeros(len(y))
        mask[train_idx] = 1
        n_train = mask.sum()
        M = A_hat @ X  # precompute -- A_hat is fixed, this is the propagated input
        for _ in range(epochs):
            Z1 = M @ self.W1 + self.b1
            H1 = np.maximum(Z1, 0)
            logits = (H1 @ self.W2 + self.b2).ravel()
            p = 1 / (1 + np.exp(-logits))
            dlogits = (p - y) * mask / n_train
            dW2 = H1.T @ dlogits.reshape(-1, 1)
            db2 = dlogits.sum()
            dH1 = np.outer(dlogits, self.W2.ravel())
            dZ1 = dH1 * (Z1 > 0)
            dW1 = M.T @ dZ1
            db1 = dZ1.sum(axis=0)
            self.W1 -= lr * dW1
            self.b1 -= lr * db1
            self.W2 -= lr * dW2
            self.b2 -= lr * db2
        return self

    def predict_proba(self, A_hat: np.ndarray, X: np.ndarray) -> np.ndarray:
        M = A_hat @ X
        H1 = np.maximum(M @ self.W1 + self.b1, 0)
        logits = (H1 @ self.W2 + self.b2).ravel()
        return 1 / (1 + np.exp(-logits))


def run_gnn_layer(df_with_features: pd.DataFrame, all_records: list[dict], cfg: dict) -> dict:
    """Builds the ring-augmented graph, trains the GCN cross-validated, and
    runs a same-architecture no-graph ablation (identity adjacency) so the
    graph's actual marginal contribution is honestly measurable rather than
    assumed."""
    X_raw = df_with_features[FEATURE_COLS].values.astype(float)
    mu, sigma = X_raw.mean(axis=0), X_raw.std(axis=0) + 1e-8
    X = (X_raw - mu) / sigma
    y = df_with_features["fraud"].values.astype(float)
    ring_mask = df_with_features["synthetic_ring"].astype(bool).values

    A = build_cross_customer_adjacency(all_records)
    A_hat = normalize_adjacency(A)
    I_hat = np.eye(len(all_records))

    gnn_folds = stable_kfold_split(df_with_features, "fraud", 5, cfg["RANDOM_STATE"])
    oof_gcn = np.zeros(len(y))
    oof_nograph = np.zeros(len(y))
    for train_idx, test_idx in gnn_folds:
        gcn = NumpyGCN(n_features=X.shape[1], seed=cfg["RANDOM_STATE"]).fit(A_hat, X, y, train_idx)
        oof_gcn[test_idx] = gcn.predict_proba(A_hat, X)[test_idx]
        nograph = NumpyGCN(n_features=X.shape[1], seed=cfg["RANDOM_STATE"]).fit(I_hat, X, y, train_idx)
        oof_nograph[test_idx] = nograph.predict_proba(I_hat, X)[test_idx]

    def summarize(proba):
        preds = (proba >= 0.5).astype(int)
        out = block(y, preds, proba)
        out["ring_subset_recall"] = float(recall_score(y[ring_mask], preds[ring_mask]))
        out["ring_subset_mean_confidence"] = float(proba[ring_mask].mean())
        return out

    return {
        "gcn_with_graph_propagation": summarize(oof_gcn),
        "ablation_identity_adjacency_no_graph_effect": summarize(oof_nograph),
        "n_synthetic_ring_traces": int(ring_mask.sum()),
        "note": "GCN standalone recall is expected to be LOWER than the XGBoost "
                "detector -- it's a deliberately simple architecture. Its value is "
                "specifically the ring_subset numbers vs. the no-graph ablation, "
                "showing genuine (if modest) benefit from graph propagation on "
                "connected fraud. Recommended production use: feed GCN score as an "
                "additional feature into the XGBoost ensemble, not standalone.",
    }


# ---------------------------------------------------------------------------
# Step 9 -- Autoencoder anomaly layer (unsupervised, zero-day catch)
#
# Trained ONLY on legitimate traces, NEVER sees a fraud label. Its
# reconstruction error is used as an anomaly score. Value proposition:
# this is the one layer in the whole system that could plausibly flag a
# completely novel GenAI fraud pattern that resembles neither ATO nor APP
# -- the supervised XGBoost model and the GCN can only ever be as good as
# the attack families they were trained on.
# ---------------------------------------------------------------------------
def run_autoencoder_layer(df_with_features: pd.DataFrame) -> dict:
    from sklearn.neural_network import MLPRegressor

    X_raw = df_with_features[FEATURE_COLS].values.astype(float)
    mu, sigma = X_raw.mean(axis=0), X_raw.std(axis=0) + 1e-8
    X = (X_raw - mu) / sigma
    y = df_with_features["fraud"].values

    legit_idx = np.where(y == 0)[0]
    ae = MLPRegressor(hidden_layer_sizes=(12, 4, 12), max_iter=1000, random_state=42, early_stopping=True)
    ae.fit(X[legit_idx], X[legit_idx])

    recon = ae.predict(X)
    recon_error = np.mean((recon - X) ** 2, axis=1)

    return {
        "legit_reconstruction_error_mean": float(recon_error[y == 0].mean()),
        "legit_reconstruction_error_std": float(recon_error[y == 0].std()),
        "fraud_reconstruction_error_mean": float(recon_error[y == 1].mean()),
        "fraud_reconstruction_error_std": float(recon_error[y == 1].std()),
        "standalone_unsupervised_roc_auc": float(roc_auc_score(y, recon_error)),
        "standalone_unsupervised_pr_auc": float(average_precision_score(y, recon_error)),
        "note": "Trained exclusively on legitimate traces -- never sees a fraud "
                "label during training. This is the zero-day / novel-pattern catch "
                "layer: it flags 'doesn't look like normal behavior' rather than "
                "'looks like a known attack family'.",
    }


def run_ablation(df: pd.DataFrame, cfg: dict) -> dict:
    """Honesty check: retrain WITHOUT the structural shortcut features
    and WITHOUT beneficiary/device presence (the two feature groups
    flagged in the module docstring as potentially inflated by
    simulator artifacts rather than genuine behavioral signal).
    Report both so the docx can show the model isn't just exploiting
    a dataset quirk.
    """
    exclude = set(STRUCTURAL_SHORTCUT_FEATURES) | {
        "beneficiary_added_before_transaction", "time_from_beneficiary_add_to_transaction",
        "new_device_present", "time_device_registration_to_transaction",
        "count_beneficiary_addition", "count_device_registration",
        # HESITATION_DELTA is derived directly from
        # time_from_beneficiary_add_to_transaction, so it's excluded
        # alongside its parent signal for the same honesty reason.
        "HESITATION_DELTA",
    }
    reduced_cols = [c for c in FEATURE_COLS if c not in exclude]
    _, calibrator, _, test_df = train_model(df, cfg, reduced_cols)
    results, _, _ = evaluate(calibrator, test_df, reduced_cols, cfg["DECISION_THRESHOLD"])
    return {"features_used": reduced_cols, "results": results["overall"], "by_family": results["by_family"]}


# ---------------------------------------------------------------------------
# Step 7 - misses.jsonl (closed-loop handoff back to Red Team)
# ---------------------------------------------------------------------------
def write_misses(test_df: pd.DataFrame, proba: np.ndarray, preds: np.ndarray, out_path: Path):
    misses = []
    for i, (idx, row) in enumerate(test_df.iterrows()):
        if row["fraud"] == 1 and preds[i] == 0:
            misses.append({
                "trace_id": row["trace_id"],
                "attack_family": row["attack_family"],
                "attack_difficulty": row["attack_difficulty"],
                "model_confidence": float(proba[i]),
                "beneficiary_signal_fired": bool(row["beneficiary_added_before_transaction"]),
                "new_device_signal_fired": bool(row["new_device_present"]),
            })
    with open(out_path, "w") as f:
        for m in misses:
            f.write(json.dumps(m) + "\n")
    print(f"  wrote {len(misses)} missed fraud cases to {out_path}")
    return misses


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    cfg = CONFIG
    out_dir = cfg["REPO_ROOT"] / cfg["OUTPUT_DIR"]
    out_dir.mkdir(exist_ok=True)

    df = build_dataset(cfg)
    df.to_csv(out_dir / "feature_table.csv", index=False)
    print(f"\nFeature table: {df.shape[0]} rows x {df.shape[1]} cols "
          f"(fraud rate: {df['fraud'].mean():.1%})")

    print("\nTraining full-feature model (single holdout split, for the saved model artifact)...")
    model, calibrator, train_df, test_df = train_model(df, cfg, FEATURE_COLS)
    holdout_results, holdout_proba, holdout_preds = evaluate(calibrator, test_df, FEATURE_COLS, cfg["DECISION_THRESHOLD"])

    print("Running 5-fold cross-validated evaluation (the number to actually trust/report)...")
    cv_results, cv_proba, cv_preds = cross_validated_evaluate(df, cfg, FEATURE_COLS, n_splits=5)

    print("Running the CASCADE (Stage 1 rule filter -> Stage 2 XGBoost) via EvaluationHarness...")
    harness = EvaluationHarness(FEATURE_COLS, cfg)
    cascade_results, cascade_proba, cascade_preds, escalate_mask = harness.run(df, n_splits=5)

    print("Running ablation (shortcut + beneficiary/device features removed), also cross-validated...")
    exclude = set(STRUCTURAL_SHORTCUT_FEATURES) | {
        "beneficiary_added_before_transaction", "time_from_beneficiary_add_to_transaction",
        "new_device_present", "time_device_registration_to_transaction",
        "count_beneficiary_addition", "count_device_registration",
        # HESITATION_DELTA is derived directly from
        # time_from_beneficiary_add_to_transaction, so it's excluded
        # alongside its parent signal for the same honesty reason.
        "HESITATION_DELTA",
    }
    reduced_cols = [c for c in FEATURE_COLS if c not in exclude]
    ablation_results, _, _ = cross_validated_evaluate(df, cfg, reduced_cols, n_splits=5)

    output = {
        "single_holdout_split_80_20": holdout_results,
        "cross_validated_5fold_ALL_FEATURES_single_stage": cv_results,
        "cross_validated_5fold_ablation_no_shortcut_or_beneficiary_device_features": ablation_results,
        "cascade_stage1_rules_plus_stage2_xgboost": cascade_results,
    }
    from artifact_metadata import stamp_artifact
    output = stamp_artifact(
        output,
        Path(__file__).parent,
        seeds={"NORMAL_WORLD_SEED": cfg.get("NORMAL_WORLD_SEED"),
               "RANDOM_STATE": cfg.get("RANDOM_STATE")},
        dataset_files=[
            cfg["REPO_ROOT"] / cfg["ATO_CORPUS_PATH"],
            cfg["REPO_ROOT"] / cfg["APP_CORPUS_PATH"],
        ],
        feature_cols=FEATURE_COLS,
    )
    with open(out_dir / "results.json", "w") as f:
        json.dump(output, f, indent=2, default=str)

    write_misses(df, cv_proba, cv_preds, out_dir / "misses.jsonl")
    joblib.dump(model, out_dir / "xgb_model.joblib")
    joblib.dump(calibrator, out_dir / "calibrator.joblib")

    print("\n=== SINGLE-STAGE 5-FOLD CV, ALL FEATURES - OVERALL ===")
    print(json.dumps(cv_results["overall"], indent=2))
    print("\n=== CASCADE (Stage 1 rules -> Stage 2 XGB) - OVERALL ===")
    print(json.dumps(cascade_results["overall"], indent=2))
    print("\n=== CASCADE - STAGE 1 DIAGNOSTICS (recall ceiling + cost savings) ===")
    print(json.dumps(cascade_results["stage1_diagnostics"], indent=2))
    print("\n=== CASCADE - BY FAMILY ===")
    print(json.dumps(cascade_results["by_family"], indent=2))
    print(f"\nAll outputs written to {out_dir}/")


if __name__ == "__main__":
    main()
